name: flood-assessment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - gdal=3.4.3
  - geopandas=0.10.2
  - rasterio=1.2.10
  - numpy=1.22.3
  - pandas=1.4.2
  - matplotlib=3.5.1
  - seaborn=0.11.2
  - scikit-learn=1.0.2
  - jupyter=1.0.0
  - notebook=6.4.11
  - flask=2.1.1
  - xarray=2022.3.0
  - netcdf4=1.5.8
  - pip=22.0.4
  - pip:
    - richdem==0.3.4
    - elevation==1.1.3
    - whitebox==2.1.2
    - rasterstats==0.16.0
    - osmnx==2.0.1
